# This is a basic workflow to help you get started with Actions

# 名字随意
name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Install and Build
        run: |
          npm install
          npm run docs:build

      # Runs a set of commands using the runners shell
      - name: Deploy
        #uses: JamesIves/github-pages-deploy-action@releases/v3
        uses:  crazy-max/ghaction-github-pages@v2
        # with:
        #   GITHUB_TOKEN: ${{ secrets.VUEPRESSTOKEN }}
        #   BRANCH: gh-pages # The branch the action should deploy to.
        #   FOLDER: docs/.vuepress/dist # The folder the action should deploy.
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: dist
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
